# Generated by Django 2.1.5 on 2019-02-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20190208_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_json',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pagetranslation',
            name='content_json',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pagetranslation',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
